"""Control-plane events generated by placement/rebalance/failover automation."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, uuid4_hex


class ControlPlaneEvent(Base, TimestampMixin):
    __tablename__ = "control_plane_events"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=uuid4_hex)
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)
    severity: Mapped[str] = mapped_column(String(16), default="info", nullable=False)
    source: Mapped[str] = mapped_column(String(64), default="control-plane", nullable=False)
    server_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("servers.id", ondelete="SET NULL"), nullable=True
    )
    payload: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    server: Mapped["Server | None"] = relationship("Server")
