[Interface]
PrivateKey = aNEaMhdroF0AM+2FObWV2GImeEPetATDYAVwYi9dink=
Address = 10.77.0.2/32
DNS = 1.1.1.1, 1.0.0.1
MTU = 1420

[Peer]
PublicKey = pFO+02mtdxIn3pe3oAj2beTHFlYw7KqB7q3I3PR9ZiY=
PresharedKey = Vp5Pv8WIiCXuFVCHKw6f+T11YlCOGlajxXVGeuh5p88=
Endpoint = 185.139.228.171:45820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
